config/routes.rb
Rails.application.routes.draw do

  
  
  root 'calculations#index'
  resources :calculations

end

app/models/calculation.rb
class Calculation < ActiveRecord::Base
    def self.total
    # your logic here
    Calculation.sum("amount")
    end
    
    def self.dept
    # your logic here
    # Account.having("sum(amount) < 0 ").sum(:amount ) 
    Calculation.where("amount < ?", 0).sum("amount")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
    def index
    @accounts = Calculation.all
    end
    
    def new
        @calculation = Calculation.new
    end
    def create
        @account = Calculation.create(idea_params)
        if @account.valid?
            # Implement later
               flash[:success] = "Your record has been posted!"
        else
            # Implement later
             flash[:alert] = "Woops! looks like there has beeen an error!"
        end
        redirect_to root_path
     end
    def edit
        @account = Calculation.find(params[:id])
    end
    def update
        @account = Calculation.find(params[:id])
     if @account.update(idea_params)
          flash[:success] = "Your record has been edited!"
        redirect_to root_path
     else
         flash[:alert] = "Woops! Looks like there has been an error!"

        redirect_to edit_idea_path(params[:id])
     end
    end
    def destroy
         @account = Calculation.find(params[:id])
        @account.destroy
        flash[:success] = "The idea was successfully deleted!"
        redirect_to root_path
    end
  private

  def idea_params
    params.require(:calculation).permit(:datetime, :title, :amount)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculations_helper.rb
module CalculationsHelper
end

app/views/calculations/edit.html.erb
      <%= simple_form_for @account, method: :patch do |f| %>
        <div class="modal-body">
          <%= f.input :title  %>
          <%= f.input :amount  %>
            <%= f.input :datetime %>
        </div>      
        <div class="modal-footer">
          <%= f.submit 'Update', class: 'btn btn-primary' %>
        </div>
      <% end %>
   

app/views/calculations/index.html.erb
<div class = "calculation">
<h1>  Balance: <%= Calculation.total-Calculation.dept  %></h1>
<h1>  Dept: <%= Calculation.dept %></h1>
<h1>  Total: <%=  Calculation.total  %></h1>
</div>

<table class="table table-hover" align="center">
    
  <thead>
    <tr>
      <th>Date</th>
      <th>Title</th>
      <th>Amount</th>
    </tr>
  </thead>
  <% @accounts.each do |account| %>
  <tbody>
    <tr>
     <th><%= account.datetime %></th>
      <th><%= account.title %></th>
      <th><%= account.amount %></th>
      <th> <%= link_to 'Delete', calculation_path(account), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"}  %>
      </th>
      <th> <%= link_to 'Edit', edit_calculation_path(account), class: 'btn btn-success' %></th>
    </tr>
    
  </tbody>
  <% end %>
</table>

app/views/calculations/new.html.erb
<%= render 'form_pages/form' %>

app/views/form_pages/_form.html.erb
    <div class="formaction">
      <%= simple_form_for Calculation.new do |f| %>
        <div class="modal-body">
          <%= f.input :title  %>
          <%= f.input :amount  %>
            <%= f.input :datetime %>
        </div>      
        <div class="modal-footer">
          <%= link_to 'Back', root_path , class: 'btn btn-primary' %> 
          <%= f.submit 'Create Record', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <link href="https://fonts.googleapis.com/css?family=Lobster&amp;subset=cyrillic,vietnamese" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id = "wrap">
    <%= render 'shared/nav' %>
    <div class = "container">
      <div class = "row">
        <% flash.each do |message_type, message| %>
          <% if message_type == "notice" %>
            <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
          <% elsif message_type == "alert" %>
            <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
          <% else %>
            <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
          <% end %>
        <% end %>
      </div>
    </div>
    <%= yield %>
  </div><!-- wrap -->

  <div class="footer text-center">
  <%= render 'shared/footer' %>
  </div>

</body>
</html>

app/views/shared/_footer.html.erb
<p>© TECHRISE <%= Date.today.year %> All Rights Reserved</p>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="#" class="navbar-brand ">Accounting</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'New Record', new_calculation_path %></li>
        <li><%= link_to 'About'%></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>
  